### ISSUE TITLE
Use developping apps with RStudio Server

### ISSUE THREAD

**Issue by bthieurmel** [datastorm-open/shinymanager#1]
At moment impossible... @pvictor : are you abled to check on Rstudio Server ? If not, I can give you an access.

**Comment by pvictor** [comment]
Mmmh ok that's not possible to clear the query string from Shiny server (at least with the method used), I removed that, it works, see here : http://shinyapps.dreamrs.fr/shiny-sqlite/

**Comment by bthieurmel** [comment]
Ok. Thanks.

**Comment by pvictor** [comment]
Ok, it works fine now : http://shinyapps.dreamrs.fr/shiny-sqlite/
It was missing `session$clientData$url_pathname` to use, which is not very useful locally
