### ISSUE TITLE
shinymanager alters the process for stopping a Shiny app

### ISSUE THREAD

**Issue by srearl** [datastorm-open/shinymanager#102]
This is a most helpful package, thank you very much for your time and effort. 

Running on Ubuntu, I am noticing that including shinymanager in a Shiny application affects how I terminate the app. Without shinymanager, I am able to kill the app/process with `Ctrl+c` whereas I am unable to kill the process when shinymanager is included (i.e., `Ctrl+c` does not have an effect). When shinymanager is included, I find that I need to put the app/process to sleep with `Ctrl+z` then explicitly kill the job with `kill`. The extra steps required to stop an app with shinymanager running are not particularly burdensome but I wonder if this has any effect on system resources or if I have set up shinymanager incorrectly. I am considering adding shinymanager to numerous Shiny apps that I run in production but would like to understand this issue better before doing so.

**Comment by bthieurmel** [comment]
Hi, do you continue to investigate this point ?

**Comment by srearl** [comment]
No, I have not been able to figure out the cause of this but thank you for the follow-up.

**Comment by srearl** [comment]
I am now seeing this behaviour in shiny applications that are not running `shinymanager` so it must stem from something else (upgrade to R 4.1.0, new Linux kernel... no telling). Thanks for your consideration and sorry for the trouble.
