### ISSUE TITLE
Adding support for new language

### ISSUE THREAD

**Issue by StatisMike** [datastorm-open/shinymanager#105]
Hi!

I would like to create a new language option for the application (Polish). Should I add only new translations in the language.R file for it to work? 

After looking through file it seems that specifically I need to:

- add `pkgEnv$label_pl` list
- new value in `v_language_registered` and its names
- modify `language$private$labels`
- new `language$private$DT_lan` list
- modify `set_labels` and `get_labels`.

**Comment by bthieurmel** [comment]
Hi @StatisMike,

You 've to : 

- add `pkgEnv$label_pl` list. 
- new value in `v_language_registered` and its names
- modify `language$private$labels`
- new `language$private$DT_lan` list
- modify `set_labels` and `get_labels`.

**You must use unicode for special char.**

After that, please sumit a Pull request and it'll be integrate quickly.

Thanks !
