### ISSUE TITLE
All images (logos) are missing after using secure_app

### ISSUE THREAD

**Issue by JWusagi** [datastorm-open/shinymanager#108]
HI there 

Thanks very much for this fantastic package - password login page works perfectly.  One minor issue is that the images I put in the www folder under the same directory are not displayed after I using secure_app, they were well shown beforehand.  

Has anyone experienced the same issue, or is there any particular way in which I can solve it? 

Many thanks,
Jie

**Comment by bthieurmel** [comment]
Hi @JWusagi,

Never have any problem rendering image with ``shinymanager``. Do you solve that ? If not, cna you send us a minimal example ?

**Comment by JWusagi** [comment]
> Hi @JWusagi,
> 
> Never have any problem rendering image with `shinymanager`. Do you solve that ? If not, cna you send us a minimal example ?

Thanks mate.  I have solved it and can see all the images by running the App by `shinyApp(ui=ui_1, server=server_1)` instead of `runApp(list(ui = ui_1, server = server_1), launch.browser = TRUE)`. 

Although I don't really understand why, it is now solved!
