### ISSUE TITLE
Export feateure on admin page

### ISSUE THREAD

**Issue by MislavSag** [datastorm-open/shinymanager#11]
Great package. I would just like to recommend one more option admin page: export table. This can be handy if I want ot deploy a new version of shiny app on shinyapp.io. If I don't export table I will lose all users.

Additionally, it would be probably better to save data on separate MySQL database, so that user info is separated from app container...

**Comment by bthieurmel** [comment]
Hi,

I've just add the possibility to export the encrypt database from the admin mode.
