### ISSUE TITLE
Password database isn't sychnronised with user database when user name is changed

### ISSUE THREAD

**Issue by StatisMike** [datastorm-open/shinymanager#112]
After changing username using admin panel (`output$table_users`), the table containing user passwords and used to menage user password (`output$table_pwds`) isn't updated accoringly. 

After editing the username, new one isn't contained withing `table_pwds`. This behaviour is seen below (using the app in `examples/demo`):

![](https://statismike.github.io/gallery/shinymanager112.png)

**Comment by bthieurmel** [comment]
Thanks. Work in progress !

**Comment by bthieurmel** [comment]
Done

**Comment by StatisMike** [comment]
Thanks, great job!
