### ISSUE TITLE
How to change the stored db password 

### ISSUE THREAD

**Issue by dcont5512** [datastorm-open/shinymanager#115]
Is it possible to change the default password that you set with shinymanager::create_db? In the example below, I would like to change the db password that I originally created ("garfield") with something else:

create_db(
  credentials_data = credentials,
  sqlite_path = "path/to/database.sqlite", 
  passphrase = "garfield"
)

**Comment by pvictor** [comment]
No it's not possible, but you can read what's in the DB and write elsewhere:

```r
# read previous db
credentials <- read_db_decrypt("database.sqlite", "credentials", passphrase = "garfield")
pwd_mngt <- read_db_decrypt("database.sqlite", "pwd_mngt", passphrase = "garfield")
logs <- read_db_decrypt("database.sqlite", "logs", passphrase = "garfield")

# write in a new db
write_db_encrypt("new_database.sqlite", credentials, "credentials", passphrase = "new_passphrase")
write_db_encrypt("new_database.sqlite", pwd_mngt, "pwd_mngt", passphrase = "new_passphrase")
write_db_encrypt("new_database.sqlite", logs, "logs", passphrase = "new_passphrase")
```

Victor
