### ISSUE TITLE
Font-Awesome Warnings 

### ISSUE THREAD

**Issue by dmenne** [datastorm-open/shinymanager#117]
Using shinymanager 1.0.400 with shiny 1.6.0.92021,  I get the warnings below when shinymanager is active. I know these Fonts are moving targets, and even core Shiny does not stay up-to-date, see a similar issue (https://community.rstudio.com/t/use-of-open-source-icons-in-shiny/110056)

However, I think this can be solved easily by using some other icon here. Trial-and-error, though, to find which ones are available.

```
Listening on http://127.0.0.1:3838
The `name` provided ('sign-out') is deprecated in Font Awesome 5:
* please consider using 'sign-out-alt' or 'fas fa-sign-out-alt' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('close') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`

**Comment by pvictor** [comment]
Icon management will change in the next version of shiny, it'll be powered by package [{fontawesome}](https://github.com/rstudio/fontawesome), you should raise this issue there, that's not related to {shinymanager}.

**Comment by ismirsehregal** [comment]
@pvictor a [related post](https://stackoverflow.com/questions/70754058/warning-using-shinymanager-font-awesome-icon-close-does-not-exist) came up on SO.

Shouldn't e.g. `icon("close")` be replaced by `icon("times")` [in this case](https://github.com/datastorm-open/shinymanager/blob/f45bc258013d8e293038017de703d8fd7f5ae6c7/R/fab_button.R#L57)?

```
icon("close")
# This Font Awesome icon ('close') does not exist:
# * if providing a custom `html_dependency` these `name` checks can 
#   be deactivated with `verify_fa = FALSE`
icon("times")
```

Cheers!

**Comment by pvictor** [comment]
You're right @ismirsehregal it should be replaced, are you willing to make a PR ?

**Comment by ismirsehregal** [comment]
@pvictor sure https://github.com/datastorm-open/shinymanager/pull/130 should fix all the warnings. Cheers
