### ISSUE TITLE
Login loop after Google authentication

### ISSUE THREAD

**Issue by benkates** [datastorm-open/shinymanager#12]
Excellent package, thank you. Within my Shiny app I'm using the [googleAuthR](https://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#googleauth-module-example) package to authenticate to Google for API pulls. When I wrap the app with shinymanager I am brought back to the shinymanager login page after authenticating with Google. Then, the Google auth does not transfer back into the session. Any help here would be appreciated.

**Comment by bthieurmel** [comment]
Hi,

Do you think it's possible to send us a simple example ?

**Comment by bthieurmel** [comment]
closed due to inactivity
