### ISSUE TITLE
Credentials database is being overwritten

### ISSUE THREAD

**Issue by kjenki49** [datastorm-open/shinymanager#13]
Hello,

I am finding that the credentials database is overwritten with the default global values whenever  reload the R studio console, deleting my updates to any users. Is this a common problem and a solution?

Many Thanks,

Kirsten

**Comment by pvictor** [comment]
Hello,
Can you provide a code sample ?
Be sure not to call `create_db` multiple times, it should be called only once to create the database.

Victor

**Comment by tinkuborah** [comment]
Hi victor,
Thanks for your previous comment. It helped me figure out my bug. I had the create_db code included in the server code which was causing the functionalities of admin ui to not work.
