### ISSUE TITLE
Multiple Users with same credentials

### ISSUE THREAD

**Issue by JuKo007** [datastorm-open/shinymanager#134]
First of all, thank you a lot for your amazing package! Shinymanager being free is amazing!

I don't have an issue but more of a question:
By default, shiny creates an isolated process for each user of the app so that no user has access to data uploaded by other users. If I'm using shinymanager and multiple people log in with the same credentials (Username + Password), are the sessions still separated from one another? I would like to limit my app to people I send credentials for logging in to, but I'd need to ensure that no data can spill over between users even when logged in with the same credentials.

**Comment by bthieurmel** [comment]
Yes, the sessions are always separated from one antoher (same credentials or not)

**Comment by JuKo007** [comment]
Great, thanks!
