### ISSUE TITLE
I would like to add support for greek language - unicode?

### ISSUE THREAD

**Issue by lefkiospaikousis** [datastorm-open/shinymanager#138]
Hi! Thanks for this great package
I am using it a lot and I would like to contribute in some way

I can add support for the Greek language
I am worried though about the greek letters and the Unicode representation

for example:
```
pkgEnv$label_gr = list(
  "Please authenticate" = "Ονομα χρήστη",
  "Username:" = "Συνθηματικό:"
...
```
Do I need to write the entire translation in Unicode? 
[Greek_script_in_Unicode](https://en.wikipedia.org/wiki/Greek_script_in_Unicode)

Thanks

**Comment by pvictor** [comment]
Hello,

In package [prefixer](https://github.com/dreamRs/prefixer) I have an addin to convert non-ascii characters, it'll transform your text like so:

```r
pkgEnv$label_gr = list(
  "Please authenticate" = "\u039f\u03bd\u03bf\u03bc\u03b1 \u03c7\u03c1\u03ae\u03c3\u03c4\u03b7",
  "Username:" = "\u03a3\u03c5\u03bd\u03b8\u03b7\u03bc\u03b1\u03c4\u03b9\u03ba\u03cc:"
)
```
I also can do it for you if you open a PR.

Victor

**Comment by lefkiospaikousis** [comment]
Great, thanks! Will do it that way
Lefkios

**Comment by lefkiospaikousis** [comment]
Thanks!
