### ISSUE TITLE
Package does not write new user

### ISSUE THREAD

**Issue by jberilo** [datastorm-open/shinymanager#149]
Good Morning.

I tried to register a new user but it seems that the app does not record when we close the app and start it again. The user disappears and I can't log in. Can you help me?

Thanks.

**Comment by pvictor** [comment]
Hello,

If you deploy your app with shinyapps.io, that's expected, there's no persistent data storage on shinyapps.io service, you can read more here : https://docs.rstudio.com/shinyapps.io/Storage.html
Your database is lost when the instance is closed, and the one you've pushed when deploying the application will be used.

Victor
