### ISSUE TITLE
Shiny server (with Docker) versus RStudio?

### ISSUE THREAD

**Issue by alexandrenicol** [datastorm-open/shinymanager#15]
Hi! 

I've been using your package to add an authentication layer to a Shiny application. 

When I launch the application using RStudio and the "Run App" button, it works perfectly.

Also, I have a continuous deployment setup, which uses AWS ECS, and a Docker Image (rocker/shiny-verse) which - I believe - contains a Shiny Server. When I try to deploy the application using the Docker image, nothing happens when I click on the Login button (same behaviour locally or on AWS).

If I remove everything related to Shinymanager and the authentication layer, the applications works on all of our platforms.

Would you have any idea what could trigger this difference in behaviour?

Thanks!
Alex

**Comment by pvictor** [comment]
Hello Alexandre,

A few questions to try to find out what's going on:

* Can you share your application ?
* Does a modal appear at the start of the application? (or any type of overlay window)
* Is there any Javascript errors in the web console ?

Thanks,

Victor

**Comment by alexandrenicol** [comment]
Hi Victor,

Thanks for your reply

- I'll need to remove a few things to share the code, there's some sensitive content.
In the meantime
- I've attached a screenshot of what I get (app + console) when I launch the application (using Docker+Shiny Server)

![Screenshot 2020-01-22 at 17 31 57](https://user-images.githubusercontent.com/6968775/72918178-1ef69f80-3d3d-11ea-807f-f2e7fe30e48a.png)

**Comment by pvictor** [comment]
Thanks for the complement. And when you click the button, nothing more ?

**Comment by bthieurmel** [comment]
closed due to inactivity
