### ISSUE TITLE
is admin module not enabled yet?

### ISSUE THREAD

**Issue by sanjmeh** [datastorm-open/shinymanager#164]
The GitHub page shows a graphical user interface (GUI) for managing users, but it doesn't clarify how to enable this in a Shiny app, nor does the package documentation. Is the admin module a feature under development or an illustration of what could be achieved with additional custom coding? Or is it existing?

This section of the documentation is confusing. Can the developers of shinymanager elaborate a little this part?
https://github.com/datastorm-open/shinymanager#admin-mode

**Comment by sanjmeh** [comment]
Seems no action on this repository for a long time. It is so sad that such a great product is left half way through by the developers. Could any one of you drop a line about the future strategy for this package please? @indubio @pvictor @erikson84 @ucg8j

**Comment by pvictor** [comment]
Package works fine and admin mode too, have you tried the code in readme ?
Further documentation is available here : https://datastorm-open.github.io/shinymanager/articles/SQLite_Admin.html

**Comment by sanjmeh** [comment]
In above code after I authenticate as shinymanager I see the test UI that I built but no sign of any admin ui.

**Comment by sanjmeh** [comment]
Oh my goodness, the gems were hidden there !! Thank you so much. You saved me so much time as I was about to start building my own user management module. This issue can be closed. Have a nice day.
