### ISSUE TITLE
password security condition relaxation

### ISSUE THREAD

**Issue by sanjmeh** [datastorm-open/shinymanager#165]
In the password change menu, the user is forced to use at least one number, one special char etc. Is there a way to bypass this or change these rules?

![image](https://github.com/datastorm-open/shinymanager/assets/3091624/3673c28a-6f2b-4cf8-a122-e64420dbb09b)

**Comment by bthieurmel** [comment]
Of course. You can use ``validate_pwd`` function.

The default is : 

````

validate_pwd <- function(pwd) {
  all(vapply(
    X = c("[0-9]+", "[a-z]+", "[A-Z]+", ".{6,}"),
    FUN = grepl, x = pwd, FUN.VALUE = logical(1)
  ))
}
````


For example, in global.R : 

````
validate_pwd_custom <- function(pwd) {
  all(vapply(
    X = c("[0-9]+", "[a-z]+", "[A-Z]+", "[[:punct:]]+", ".{8,}"),
    FUN = grepl, x = pwd, FUN.VALUE = logical(1)
  ))
}
````

And use in server.R : 

````
    auth_out <- secure_server(...,
        validate_pwd = validate_pwd_custom
    )
````

**Comment by sanjmeh** [comment]
saved for testing in our project.
