### ISSUE TITLE
Log failed logins

### ISSUE THREAD

**Issue by panuffel** [datastorm-open/shinymanager#177]
Hi. With shinymanager, I can log users that successfully logged into my application, but I need to track failed logins to cover possible hacks. What I found in the manuals is the possibility to limit the number of password failures via:

options("shinymanager.pwd_failure_limit" = 5)

However, this did not work for me (maybe I placed it wrong...). Could you please provide a working example with limited failures or a way to log failures?

**Comment by panuffel** [comment]
I found a 'solution' now by adding print commands into function `credentials_df` and overwriting it via
`assignInNamespace("check_credentials_df", my_check_credentials_df, ns = "shinymanager")`

**Comment by marcusyoung** [comment]
`options("shinymanager.pwd_failure_limit" = 5)`  should be placed in secure_app(), not secure_server(). It works for me.
