### ISSUE TITLE
Internet explorer doesn't support the method 'includes'

### ISSUE THREAD

**Issue by conrad-mac** [datastorm-open/shinymanager#18]
When trying to run an app with `shinymanager` in internet explorer, neither the logout nor timeout functions work. The error in the console is below. This actually crashes the running of JavaScript in my app and so doesn't load the select input element etc. No problems on Chrome or Edge, however.

![image](https://user-images.githubusercontent.com/16858723/75199307-a5345480-57c7-11ea-9989-5d60efaaf45e.png)

**Comment by pvictor** [comment]
Hello,
Yes `includes` is indeed not available in IE, we can use `array.indexOf(i) !== -1` or a polyfill ( as defined here : https://mariusschulz.com/blog/ecmascript-2016-array-prototype-includes

**Comment by bthieurmel** [comment]
Hi, this is fixed on dev version.

**Comment by conrad-mac** [comment]
I can confirm that this change has fixed my issue. Thanks so much for the quick response!
