### ISSUE TITLE
Customize "Please authenticate", "Username:" and "Password:"

### ISSUE THREAD

**Issue by aephidayatuloh** [datastorm-open/shinymanager#19]
Hi, this is great package.

I need advice to customize the "Please authenticate", "Username:" and "Password:" with my own text or remove it. Is it possible to do in `secure_app()` or `auth_ui()`?
Thank you.

**Comment by bthieurmel** [comment]
Hi,

It's now possible using dev version with new function ``set_labels``

``
# ?set_labels
# global.R
set_labels(
  language = "en",
  "Please authenticate" = "",
  "Username:" = "What's your name:",
  "Password:" = "Enter your password:"
)
``

**Comment by aephidayatuloh** [comment]
Thanks @bthieurmel, this solved
