### ISSUE TITLE
Reset pwd : don't validate if user puts old pwd

### ISSUE THREAD

**Issue by bthieurmel** [datastorm-open/shinymanager#2]
New pwd must be different than old

**Comment by pvictor** [comment]
Yes that make sense.
I think we need a password validation method, for example there's no requirement on length for now

**Comment by bthieurmel** [comment]
Yes. Regular expression ?

**Comment by pvictor** [comment]
Something like : 

```r
vapply(
  X = c("[0-9]+", "[a-z]+", "[A-Z]+", ".{6,}"),
  FUN = grepl, x = "a2cdeF", FUN.VALUE = logical(1)
)
```
At least one number, one lowercase, one uppercase, and minimal length 6 ?

**Comment by bthieurmel** [comment]
Yes, why not. And add the possibility for the developper to enter his condition ?

**Comment by pjbulls** [comment]
I see the password validation function was added in the meantime and exposed in `pwd_server`, but there isn't a way for the user to actually add a custom validation function to `secure_server`. It seem slike just adding a placeholder NULL argument to the latter would make that possible and not break anything?
