### ISSUE TITLE
Additional column in the shiny admin page

### ISSUE THREAD

**Issue by tinkuborah** [datastorm-open/shinymanager#20]
Hi,

 Thanks for your effort in developing this.
I was wondering if there is an option to add a custom column(eg comments) that shows up in the
the shiny admin page. If we can retrieve the value of the column by using something like 
res_auth <- secure_server(
        check_credentials = check_credentials("complexity.sqlite", passphrase = "abcd")
)
 comments<- reactiveValuesToList(res_auth)$comments

This comments can be used for providing customized access at user level which can be directly provided from the admin page.

Please let me know if this is already available.

Thanks
Tinku

**Comment by bthieurmel** [comment]
Hi, 

You can use all custom columns you want, and retrieve the values in R : 

````
credentials <- data.frame(
  user = c("shiny", "shinymanager"),
  password = c("shiny", "shinymanager"),
  group = c("all", NA),
  comment = c("Easy interactive web applications with R",
              "Simple and secure authentification mechanism for single 'Shiny' applications."),
  admin = c(FALSE, TRUE),
  stringsAsFactors = FALSE
)

# Create credentials DB (only once)
create_db(
  credentials_data = credentials,
  sqlite_path = "credentials.sqlite",
  passphrase = "supersecret"
)

library(shiny)
library(shinymanager)

ui <- fluidPage(
  tags$h2("My secure application"),
  verbatimTextOutput("auth_output")
)

# Wrap your UI with secure_app
ui <- secure_app(ui)

server <- function(input, output, session) {
  
  # call the server part
  # check_credentials returns a function to authenticate users
  res_auth <- secure_server(
    check_credentials = check_credentials(
      db = "credentials.sqlite",
      passphrase = "supersecret"
    )
  )
  
  output$auth_output <- renderPrint({
    reactiveValuesToList(res_auth)
  })
}

shinyApp(ui, server)
````

**Comment by tinkuborah** [comment]
@bthieurmel ... Thanks a lot for the code snippet. It works perfect. Appreciate it.
