### ISSUE TITLE
use shinymanager with 3 files: global.R, ui.R, server.R

### ISSUE THREAD

**Issue by dsaada** [datastorm-open/shinymanager#21]
Hi,

I would like to use shiny manager on my app, but this app use 3 files.

How to use it?

thanks

**Comment by pvictor** [comment]
Hello,

{shinymanger} works very well using three files, you can find exemples in sub-folders here : https://github.com/datastorm-open/shinymanager/tree/master/dev

If the documentation is not clear, do not hesitate to let us know

Victor
