### ISSUE TITLE
Keep login after refresh(F5)

### ISSUE THREAD

**Issue by jinseob2kim** [datastorm-open/shinymanager#23]
Thanks for great packages.

Can I **keep my ShinyApps log in** after refresh (ex: press F5) ? 
- My app reads the latest data from google sheet or Dropbox. So I refresh it frequently.

Sincerely.
Jinseob Kim

**Comment by bthieurmel** [comment]
Hi, perhaps in your case you lust have a look to ``shiny::reactiveFileReader`` to update Data in session rather than have to refresh ?

**Comment by jinseob2kim** [comment]
Thanks for your suggestion. I didn't know about `reactiveFileReader` function. 
As I know, the function requires  specific refresh interval and I can't decide the appropriate interval. 
Currently, I add a **refresh** button to app, but my clients prefer to press F5, so our team try to find a solution. 

Sincerely.

Jinseob Kim

**Comment by pvictor** [comment]
Hello,

To allow refresh the page, we'll have to keep to the shinymanager token used to grant access to the app in the URL, if you're ok with that, we can add this as an option. What do you think?

Victor

**Comment by jinseob2kim** [comment]
@pvictor  The solution is best for me. Thanks!!
