### ISSUE TITLE
Extract username

### ISSUE THREAD

**Issue by muntean-alex** [datastorm-open/shinymanager#27]
Hi,

Would it be possible to extract the username that has logged in?
I want to use this to filter the df according to user rights.

I wanted to make an encrypted file with bcrypt for extra security.
Have you ever considered this?

**Comment by aephidayatuloh** [comment]
Hi, 
Just share my experince about this. For example, assume you use `secure_server()` inside the server function.

```
auth <- secure_server(
  check_credentials = check_credentials(credentials)
)
```

You can get the username with `auth$user` or `auth$user_info$user`. You also can get other information that correspond to your credentials table with `auth$user_info$<column>`.
CMIIW

**Comment by BrianCollinss** [comment]
Hey guys. I wonder if you have a way to send the username to the UI side. I see that we can have **reactiveValuesToList(res_auth)** on the server side. But I can only send a text to the UI side, not the username. I am trying to have different UI layour for dofferent users.

**Comment by northernstream** [comment]
@BrianCollinss  Would this snippet be of any help?
` res_auth <- secure_server(
    check_credentials = check_credentials(credentials)
  )
  output$auth_output <- renderPrint({
    reactiveValuesToList(res_auth)
  })
  `
