### ISSUE TITLE
User signup

### ISSUE THREAD

**Issue by ricschuster** [datastorm-open/shinymanager#3]
Great package!

Do you have plans to add user signup capability as well?
Would be great if users could sign up and are allowed to sign in once they verify their email or an admin flags them as approved.

**Comment by bthieurmel** [comment]
Hi,
At moment, waiting for more friendly interface (but more complex...!), you can just add : some message / contact in the ``auth_ui`` to demand for example an account to somebody : 

````
# authentication module
    auth_ui(
      id = "auth",
      tag_img = tags$img(
        src = "https://www.r-project.org/logo/Rlogo.png", width = 100
      ),
      tag_div = tags$div(
        tags$p(
          "For any question, please  contact ",
          tags$a(
            href = "mailto:someone@example.com?Subject=Shiny%20aManager",
            target="_top", "administrator"
          )
        )
      )
    )
````

**Comment by ricschuster** [comment]
Thanks! Will give that a try.
