### ISSUE TITLE
Support for Postgresql Connection

### ISSUE THREAD

**Issue by bernorev** [datastorm-open/shinymanager#30]
Hi,

Is it possible to add support for a postgres connection? Would be especially useful for shinyapps deployment where sqlite won't work.

Thanks!

**Comment by tedmoorman** [comment]
This would be helpful.

**Comment by tedmoorman** [comment]
Good suggestion @vikram-rawat . We could add an option to the necessary package functions to choose a database type. Then we could update the code to reflect a user's database.

**Comment by pvictor** [comment]
Hi,
You can use your own function to check a user and use any DBI connection you want, minimal example:

```r
library(shiny)
library(shinymanager)

my_custom_check_creds <- function(user, password) {
  con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
  DBI::dbWriteTable(con, "my_table", data.frame(
    user = c("test"),
    password = c("123"),
    stringsAsFactors = FALSE
  ))
  req <- sqlInterpolate(
    conn = con, 
    sql = "SELECT * FROM my_table WHERE user = ?user AND password = ?password", 
    user = user,
    password = password
  )
  res <- DBI::dbGetQuery(con, statement = req)
  if (nrow(res) > 0) {
    list(result = TRUE, user_info = list(user = user, something = 123))
  } else {
    list(result = FALSE)
  }
}

ui <- fluidPage(
  tags$h2("My secure application"),
  verbatimTextOutput("auth_output")
)
ui <- secure_app(ui)


server <- function(input, output, session) {
  res_auth <- secure_server(
    check_credentials = my_custom_check_creds
  )  
  output$auth_output <- renderPrint({
    reactiveValuesToList(res_auth)
  })

}

shinyApp(ui, server)
```

Victor

**Comment by tedmoorman** [comment]
When I do this, it says my username or password are incorrect. I verified that the user and password in the database are correct. There is also a row.names column. Not sure what the reason is.

**Comment by vikram-rawat** [comment]
In this scenario how can I utilize createDB function on a postgres database. Because that's an essential part of saving the credentials...

**Comment by rtrad89** [comment]
> 
> 
> Hi,
> You can use your own function to check a user and use any DBI connection you want, minimal example:
> 
> ```r
> library(shiny)
> library(shinymanager)
> 
> my_custom_check_creds <- function(user, password) {
>   con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
>   DBI::dbWriteTable(con, "my_table", data.frame(
>     user = c("test"),
>     password = c("123"),
>     stringsAsFactors = FALSE
>   ))
>   req <- DBI::sqlInterpolate(
>     conn = con, 
>     sql = "SELECT * FROM my_table WHERE user = ?user AND password = ?password", 
>     user = user,
>     password = password
>   )
>   res <- DBI::dbGetQuery(con, statement = req)
>   if (nrow(res) > 0) {
>     list(result = TRUE, user_info = list(user = user, something = 123))
>   } else {
>     list(result = FALSE)
>   }
> }
> 
> ui <- fluidPage(
>   tags$h2("My secure application"),
>   verbatimTextOutput("auth_output")
> )
> ui <- secure_app(ui)
> 
> 
> server <- function(input, output, session) {
>   res_auth <- secure_server(
>     check_credentials = my_custom_check_creds
>   )  
>   output$auth_output <- renderPrint({
>     reactiveValuesToList(res_auth)
>   })
> 
> }
> 
> shinyApp(ui, server)
> ```
> 
> Victor

This example is quite handy, but I want to point out the following when working with `PostgreSQL`:

- > Using ? to mark parameters in a query does not currently work with RPostgres, instead use $ ([src](https://db.rstudio.com/best-practices/managing-credentials/#stored-in-a-file-with-config))
- The example assumes the developer uses the same credential to connect to the database and to access the application for brevity. If this is not the case, and since it is not recommended to store DB connection details in the code, a `yml` configuration file can be use instead (see [this](https://db.rstudio.com/best-practices/managing-credentials/#stored-in-a-file-with-config))

@tedmoorman your problem may be related to the first point.

**Comment by bthieurmel** [comment]
You can pass all arguments you want (.yml, config, ....) like this : 

````R
require(RPostgreSQL)
library(shiny)
library(shinymanager)
library(DBI)
library(glue)

dbname = "*****"
host = "localhost"
port = *****
user = "*****"
password = "******"

con <- dbConnect(dbDriver("PostgreSQL"), dbname = dbname , host = host, port = port ,
                 user = user, password = password )


DBI::dbWriteTable(con, "my_table", data.frame(
  user = c("test"),
  password = c("123"),
  stringsAsFactors = FALSE
))

# or a config .yml file or others arguments
my_custom_check_creds <- function(dbname, host, port, db_user, db_password) {
  
 # finally one function of user and password
  function(user, password) {
    
    con <- dbConnect(dbDriver("PostgreSQL"), dbname = dbname, 
                     host = host, port = port,
                     user = db_user, password = db_password)
    
    on.exit(dbDisconnect(con))
    
    req <- glue_sql("SELECT * FROM my_table WHERE \"user\" = ({user}) AND \"password\" = ({password})", 
             user = user, password = password, .con = con
    )
    
    req <- dbSendQuery(con, req)
    res <- dbFetch(req)
    if (nrow(res) > 0) {
      list(result = TRUE, user_info = list(user = user, something = 123))
    } else {
      list(result = FALSE)
    }
  }
}

ui <- fluidPage(
  tags$h2("My secure application"),
  verbatimTextOutput("auth_output")
)
ui <- secure_app(ui)


server <- function(input, output, session) {
  res_auth <- secure_server(
    check_credentials = my_custom_check_creds(
      dbname = "******",
      host = "*****",
      port = ****,
      db_user = "*****",
      db_password = "*******"
    )
  )  
  auth_output <- reactive({
    reactiveValuesToList(res_auth)
  })
  
  # access info
  observe({
    print(auth_output())
  })
}

shinyApp(ui, server)
````

**Comment by devops-qubits** [comment]
I have a working app with shinymanager and Postgres on AWS. Is there any way to enable admin mode with Postgres?
Apparantly admin  is only available using a SQLite database.

**Comment by bthieurmel** [comment]
SQL support in developpement, with admin & logs module. Coming soon
