### ISSUE TITLE
Problem with set_labels

### ISSUE THREAD

**Issue by ghnunes** [datastorm-open/shinymanager#32]
Hello, when I try to run examples / demo there is an error in the file globol.r, in this excerpt:

set_labels (
   language = "en",
   "Please authenticate" = "You have to login",
   "Username:" = "What's your name:",
   "Password:" = "Enter your password:"
)
Error in set_labels (language = "en", `Please authenticate` =" You have to login ",:
   could not find function "set_labels"
I installed the library library (sjmisc), but it's still giving an error, do you know why?

**Comment by Oliversinn** [comment]
Did you solve the problem? I'm having the same issue...

**Comment by pvictor** [comment]
Hello,

Can you provide the result of `sessioninfo::session_info()` ?
Thanks
