### ISSUE TITLE
observe ({ }) is not working when I do the same using shinymanager

### ISSUE THREAD

**Issue by krinya** [datastorm-open/shinymanager#34]
Everything works fine but it seems like the observe withing the shiny-server is giving me an error when I use it with shinymanager.

Is anyone getting the same error?

**Comment by pvictor** [comment]
Hello,
Can you provide an example to reproduce the problem please ?
Thanks,

Victor

**Comment by bthieurmel** [comment]
Perhaps you can have a look to #36
