### ISSUE TITLE
URL parameter processing

### ISSUE THREAD

**Issue by DereMann** [datastorm-open/shinymanager#39]
Hello,

I want to use your package for an shiny application where the application state is stored in URL parameters: https://shiny.rstudio.com/articles/bookmarking-state.html

When I add your package to my app the bookmarking feature via URL params does not work anymore as it seems the params are not being considered by your redirects?

Many thanks and BR

**Comment by bthieurmel** [comment]
Hi,

I've just push a fix for using shiny bookmarking with ``shinymanger`` on branch master.

If you want to try...
