### ISSUE TITLE
documentation for `auth_server` and argument `check_credentials`

### ISSUE THREAD

**Issue by FelixErnst** [datastorm-open/shinymanager#40]
Hi,

I have a question regarding the documentation for the `check_credentials` argument of the `auth_server`/`secure_server` function. In the man pages is stated:

> check_credentials | Function with two arguments (user, the username provided by the user and password, his/her password). Must return TRUE or FALSE. To use additionnals arguments, set them with purrr::partial (see examples).

However, when trying to implement a custom function I got an error/warning `Warning: Error in $: $ operator is invalid for atomic vectors`. After investigating the default `check_credentials` and `check_credentials_df` function, it became clear that there is bit of deviation between code and man page.

`check_credentials_df` always returns a `list` with several named elements, e.g `auth <- list(result = FALSE, expired = FALSE, authorized = authorized,  user_info = user_info)`

Would you have the time to clarify this situation and how, you see alternative functions to implemented correctly? Thanks

Felix

**Comment by pvictor** [comment]
Hello,

My bad, the documentation is wrong. 
Originally the value was supposed to be TRUE/FALSE, but we added options like expired, user_infos... and we had to use a `list` and I didn't update the documentation.

Is that ok to you to use a list ? Maybe we can do something to still work with TRUE/FALSE

I'll update the documentation anyway

Victor

**Comment by FelixErnst** [comment]
Hi,

The documentation fix would be really nice. Thanks.

I wouldn't mind working with a complex return value, but I would suggest, that the return value is checked for validity, so that the case of an invalid return value from a user supplied function results in a meaningful error message.

Felix

**Comment by bthieurmel** [comment]
Documentation up to date
