### ISSUE TITLE
How to enter the administrator mode

### ISSUE THREAD

**Issue by Liripo** [datastorm-open/shinymanager#44]
How to enter the administrator mode, the admin is clearly set to TRUE, but there is no interface on your document after entering the shiny。

**Comment by Liripo** [comment]
And my shiny at last is
```R
server <- function(input, output, session) {
  res_auth <- secure_server(
    check_credentials = check_credentials(credentials,
      passphrase = key_get("liripo")))
}
####验证后登录
ui <- secure_app(ui)
#------------------------------
shinyApp(ui, server)
```
And the credentials is 
![image](https://user-images.githubusercontent.com/54770415/86438924-0e117780-bd3a-11ea-8f16-f32489c9fdd6.png)

```

**Comment by bthieurmel** [comment]
Hi,

Admin is only available using ``sqlite``, but I thinks this is your case.

After logging on the app, your normally can see a round button on bottom right of the page. You can access to admin page with this button : 

![image](https://user-images.githubusercontent.com/8750326/86444310-d9d59100-bd10-11ea-8c41-d912868c8266.png)

**Comment by Liripo** [comment]
Hello Developer:
   I has use sqlite,and my code is
```R
library(DBI)
library(shiny)
library(shinymanager)
library(keyring)
library(DBI)
library(keyring)
conn <- DBI::dbConnect(RSQLite::SQLite(), dbname = "database.sqlite")
credentials <- read_db_decrypt(conn = conn, 
  name = "credentials", passphrase = key_get("liripo"))
ui <- fluidPage()
ui <- secure_app(ui)
server <- function(input,output,session){
  res_auth <- secure_server(
    check_credentials = check_credentials(credentials,
      passphrase = key_get("liripo")))
}
shinyApp(ui,server)
```
and the R object is 
```R
> conn %>% dbListTables()
[1] "credentials" "logs"        "pwd_mngt"   
> credentials
    user
1 liripo
                                                                                                                          password
1 c2NyeXB0ABAAAAAIAAAAAf0X+5eXmQjdoyQuQz4abbRQhZZDhQf8OjD9fEJs/ULo6XBlSSi/bD+gJbYOlsR0rR6caIqYP/DMaxFeilJTC2CxF81qIIlp34MK+6GFfrXp
  start expire admin is_hashed_password
1  <NA>   <NA>  TRUE               TRUE
```
**the database.sqlite is in my work dir**

but my shiny after enter is
![image](https://user-images.githubusercontent.com/54770415/86448049-cc3bfd80-bd48-11ea-91bc-790ebe19e3e3.png)

Is my usage wrong? I hope you can help me！
Thank you~

**Comment by bthieurmel** [comment]
I think I understand the mistake. Using a ``sqlite`` database, you've just have to pass directly the path of the database and not the export data to ``secure_server``

````
  auth_out <- secure_server(
    check_credentials = check_credentials("database.sqlite", key_get("liripo"))
  )
````

**Comment by Liripo** [comment]
The result is still like this.
![image](https://user-images.githubusercontent.com/54770415/86449741-2d64d080-bd4b-11ea-8aab-074b37926593.png)
and my code is
![image](https://user-images.githubusercontent.com/54770415/86449817-49687200-bd4b-11ea-8188-f04d6117be5d.png)

**Comment by bthieurmel** [comment]
And probably missing ``secure_app(ui, enable_admin = TRUE)``

**Comment by Liripo** [comment]
oh,thanks for your help.It can work well.~~
