### ISSUE TITLE
Add complete example using keyring and sqlite database

### ISSUE THREAD

**Issue by gadenbuie** [datastorm-open/shinymanager#5]
First, thanks for this fantastic package -- it's almost magical!

I have a small documentation-related suggestion. The README on the front page demonstrates *creating* an encrypted sqlite credential store, but it stops short of demonstrating how `shinymanager` expects the app developer to incorporate the encrypted database into the app. I think I've pieced it together from the help documentation in `?db-crypted`, but that documentation also doesn't feature a full app. It would be great for the documentation to recommend an easy path and demo the full use case.

**Comment by pvictor** [comment]
Hello,
Thank you very much!

Sure we can improve documentation. Managing password is not in the scope of the package, but we can provide some documentation to do so.
My main resources on the subject are : 

 * https://cran.r-project.org/web/packages/httr/vignettes/secrets.html
 * https://db.rstudio.com/best-practices/managing-credentials/

A vignette with the full process will be great, I'm going to write one.

Victor

**Comment by gadenbuie** [comment]
Great! Thanks for the resources, I'm looking forward to reading the vignette!

**Comment by kiwimic** [comment]
Hello,

 I'm also looking forward to reading the vignette! Even now without DB this projects solves a lot of problem with user passwords. 

@pvictor if you need any help. I could help with vignette.
