### ISSUE TITLE
Issue in secure_app

### ISSUE THREAD

**Issue by Kaushikbharat** [datastorm-open/shinymanager#50]
I was trying to use set_labels using GitHub version ‘1.0.300’ but it is giving me an error with the language argument of the secure_app function but its not the case with ‘1.0.200’ its working fine. Can you please help.
Thanks in advance.

**Comment by bthieurmel** [comment]
Hi, 

``set_labels`` came with ``1.0.210`` I think and is not available in ``1.0.200``. Can you give us a example ?

**Comment by Kaushikbharat** [comment]
can you please let me know that version 1.0.210 is available on cran or not, if not form where can I download it?
Also, I used the latest version 1.0.300 Github version.

**Comment by bthieurmel** [comment]
``1.0.210`` is not on CRAN. This is a ``dev`` version. New CRAN version is ``1.0.300``.

Between ``1.0.200`` and ``1.0.300``, we made some dev on ``set_labels`` function.

First, it was like this : 

````
set_labels <- function(...) {
    ...
}
````

And finally on current supported version : 

````
set_labels <- function(language, ...) {
    ...
}
````

I think it's better to change / update your code to work with ``1.0.300``. I can help you if you send me an example.

**Comment by Kaushikbharat** [comment]
Thanks a lot, I installed the development version but I missed the language parameter to be given there.
This is not an issue then, actually I just copy-pasted the given example but it didn't work out.
Really appreciate the time you gave to this query.
Thanks a lot again, Its working for me as of now. I must say this is an awesome package.
Also, I need to ask one thing that is there a way I can change the position of the login modal as currently it always comes in the center but can I change its position.
