### ISSUE TITLE
Cannot add new user or write any data to the db when running in shiny server.

### ISSUE THREAD

**Issue by GeorgeOduor** [datastorm-open/shinymanager#52]
Dear all, anyone facing this problem too? I have just deployed my app on shiny-server but seems i cannot write new data to the database.

I am using shinymanager for authentication.

Is this a problem with shinymanager or SQLite.

Kindly assist.

error logs.

```
Listening on http://127.0.0.1:39899
Warning: shinymanager: unable to save logs | error: attempt to write a read-only database
```

Kindly assist.

**Comment by adamtaiti** [comment]
It seems you do not have permission to change the sqlite file. Try to change the permissions for groups and others

**Comment by GeorgeOduor** [comment]
Thanks for this sugestion.I got a solution through this.
