### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by EAMI91** [datastorm-open/shinymanager#54]
In version 1.0.200, I could change the language using lang$add. Now I think adding language isn't enabled. Am I correct? I have a list of settings to add Spanish, would you mind setting up Spanish as an eligible language?

lang <- shinymanager:::language$new()
lang$add(
  "Please authenticate" = "Favor de autenticarse",
  "Username:" = "Usuario:",
  "Password:" = "Contraseña:",
  "Login" = "Iniciar sesión",
  "Username or password are incorrect" = "Usuario o contraseña incorrecto",
  "Your account has expired" = "Su cuenta ha expirado",
  "Please change your password" = "Por favor, cambie su contraseña",
  "New password:" = "Nueva contraseña:",
  "Confirm password:" = "Confirme contraseña:",
  "Update new password" = "Actualizar nueva contraseña",
  "Password successfully updated! Please re-login" = "¡Cambio de contraseña exitoso! Por favor, vuelva a iniciar sesión",
  "The two passwords are different" = "Las dos contraseñas son diferentes",
  "Failed to update password" = "Falló la actualización de la contraseña",
  "Logout" = "Cerrar sesión",
  "Go to application" = "Ir a aplicación",
  "Administrator mode" = "Modo administración",
  "Add a user" = "Agregar usuario",
  "Failed to update user" = "Falló la actualización del usuario",
  "User successfully updated" = "Usuario actualizado correctamente",
  "Cancel" = "Cancelar",
  "Confirm new user" = "Confirmar nuevo usuario",
  "Confirm change" = "Confirmar cambio",
  "Are you sure to remove user(s): %s from the database ?" = "¿Está seguro de remover el(los) usuario(s): %s de la base de datos?",
  "Delete user(s)" = "Borrar usuario(s)",
  "Delete user" = "Borrar usuario",
  "Edit user" = "Editar usuario",
  "User already exist!" = "¡Usuario ya existente!",
  "Dismiss" = "Descartar",
  "New user %s succesfully created!" = "¡Nuevo usuario %s creado satisfactoriamente!",
  "Ask to change password" = "Pedir que cambie la contraseña",
  "Confirm" = "Confirmar",
  "Ask %s to change password on next connection?" = "¿Desea pedir a %s que cambie la contraseña en su siguiente connexión?",
  "Change saved!" = "¡Cambio guardado!",
  "Failed to update the database" = "Falló la actualización de la base de datos",
  "Password does not respect safety requirements" = "La contraseña no contiene los requerimientos de seguridad",
  "Password must contain at least one number, one lowercase, one uppercase and must be at least length 6." = "La contraseña debe contener al menos un número, una mínuscula, una mayúscula y debe ser de almenos seis caracteres.",
  "Number of connections per user" = "Número de conexiones por usuario",
  "Number of connections per day" = "Número de conexiones por día",
  "Total number of connection" = "Total de conexiones",
  "You can\'t remove yourself!" = "No puede eliminarse usted mismo",
  "User:" = "Usuario:",
  "Period:" = "Periodo:",
  "Last week" = "Semana pasada",
  "Last month" = "Mes pasado",
  "All period" = "Todo el periodo",
  "Home" = "Inicio",
  "Select all shown users" = "Seleccionar todos los usuarios mostrados",
  "Remove selected users" = "Remover los usuarios seleccionados",
  "Force selected users to change password" = "Forzar a los usuarios seleccionados que cambien la contraseña",
  "Users" = "Usuarios",
  "Passwords" = "Contraseñas",
  "Download logs database" = "Descargar la base de datos de registros",
  "Download SQL database" = "Descargar la base de datos SQL",
  "Reset password for %s?" = "Reiniciar contraseña para %s?",
  "Reset password" = "Reiniciar contraseña",
  "Temporary password:" = "Contraseña temporal:",
  "Password succesfully reset!" = "¡Contraseña reiniciada satisfactoriamente!",
  "You are not authorized for this application" = "No estás autorizado para esta aplicación",
  "Logs" = "Registros"
)

**Comment by pvictor** [comment]
Hello,

In last CRAN release (v1.0.300), you have a new function `set_labels()`, that you can use like this:

```r
library(shiny)
library(shinymanager)

set_labels(
  language = "en",
  "Please authenticate" = "Favor de autenticarse",
  "Username:" = "Usuario:",
  "Password:" = "Contraseña:",
  "Login" = "Iniciar sesión"
)


ui <- secure_app(fluidPage(
  "Connected!"
))

server <- function(input, output, session) {
  credentials <- data.frame(
    user = c("shiny", "shinymanager"),
    password = c("azerty", "12345"),
    stringsAsFactors = FALSE
  )
  secure_server(
    check_credentials = check_credentials(credentials)
  )
}


shinyApp(ui, server)
```

Thanks for all the translation, we'll add it, if you want to make a Pull request, don't hesitate, it will be faster, the file to update is this one: https://github.com/datastorm-open/shinymanager/blob/master/R/language.R

Victor
