### ISSUE TITLE
Can you use a SQL Lite data base from a DBI Connection? 

### ISSUE THREAD

**Issue by ngodoym** [datastorm-open/shinymanager#57]
Hi !
 
I was wondering if it´s possible to give the sql lite data base in the check_credentials() function from a DBI connection? Mi goal is to create docker images of my app and that all the deployed images connect to the same SQL Lite data base for the authentication process from another server. It is possible? 

Thanks !

**Comment by pvictor** [comment]
Hello,

How do you connect to your SQLite database ? Currently you can only pass argument `dbname` to `dbConnect`.
It's possible to use docker volumes so that the SQLite database live outside the container.

Victor
