### ISSUE TITLE
No log update with shiny server

### ISSUE THREAD

**Issue by jinseob2kim** [datastorm-open/shinymanager#6]
Thanks for great packages. I have 1 question.

I can get log data with local ShinyApps. 

But running with shiny server, I can't get updated log data.

Can I get log data with shiny server?

Sincerely

**Comment by bthieurmel** [comment]
Hi,

Can you update / create / delete user ? If not, it seems to be a database permissions error. The user running shinyserver (shiny bt defaut) must have read and write permissions to the database.

**Comment by jinseob2kim** [comment]
Thanks!
I get the logs after  `chmod 777 -R <shiny directory>`

**Comment by owbezick** [comment]
Hi, I just wanted to follow up on this. I am able to update/create/delete users, but my logs do not show up when deployed, only when running locally.
