### ISSUE TITLE
.tok$is_valid_timeout error

### ISSUE THREAD

**Issue by Rhydderch** [datastorm-open/shinymanager#61]
Hi,

I'm encountering the following errors, once I enter my credentials (the app loads for a second then closes and shows these errors):
``` r
Warning in .tok$is_valid_timeout(token, update = FALSE) :
  Incompatible methods ("Ops.difftime", "Ops.data.frame") for "<="
Warning: Error in .tok$is_valid_timeout: 'list' object cannot be coerced to type 'double'
  [No stack trace available]
```

The code for the server and ui I'm using can be found here (I'm using the golem package to develop the app): https://gist.github.com/Rhydderch/1b3cc0f85d318ebe92f5f7b86f57f882

**Comment by bthieurmel** [comment]
Hi, 

I think there is a mistake in your code : 

````
  res_auth <- secure_server(
    print(credentials),
    check_credentials = check_credentials(credentials)
  )
````

Due to ``print(credentials``. Just remove this line : 

````
  res_auth <- secure_server(
    check_credentials = check_credentials(credentials)
  )
````

**Comment by Rhydderch** [comment]
Thank you so much for checking it. Removing the print() solved it.
