### ISSUE TITLE
Set_Labels Img Src

### ISSUE THREAD

**Issue by JoaquinTavella** [datastorm-open/shinymanager#64]
Hi! first of all thank you for this amazing package.
I would like to know if it's possible to put a img insteed of please authenticate

set_labels(language = "en",
           "Please authenticate" = tags$img(src="https://i.ibb.co/vQv7gyr/logovertical.png"))

I used this but it only shows the image for a second and then dissapear, can you help me with this?

**Comment by pvictor** [comment]
Hi,

You can use an image directly in `secure_app`:

```r
secure_app(
  ui = ui, 
  tags_top = tagList(
    tags$img(src = "https://www.r-project.org/logo/Rlogo.png", width = 100)
  )
)
```

To remove `"Please authenticate"`, you can set the label as `NULL`.

Victor
