### ISSUE TITLE
Correct Way to Create Custom Logout Button?

### ISSUE THREAD

**Issue by yusuzech** [datastorm-open/shinymanager#7]
Logout button UI is automatically generated when using `secure_app()`. However, when using `auth_ui()`, it seems like we need to add logout UI manually. Though we can create logout UI using `fab_button()`, it seems like the logging-out logic is not automatically added and we need to write our own server code for logging out.

```
  observeEvent(session$input$logout,{
    session$reload()
  })
```
Is there a built-in or better way to to log out when using `auth_ui()`? 

Thanks.

Custom logout example(adapted from example in `auth_ui()`):
```r
library(shiny)
library(shinymanager)

# data.frame with credentials info
credentials <- data.frame(
  user = c("fanny", "victor"),
  password = c("azerty", "12345"),
  stringsAsFactors = FALSE
)

# app
ui <- fluidPage(
  # authentication module
  auth_ui(id = "auth"),
  fab_button(
    actionButton(
      inputId = "logout",
      label = NULL,
      tooltip = "Logout",
      icon = icon("sign-out")
    )
  )
  
)

server <- function(input, output, session) {
  
  # authentication module
  auth <- callModule(
    module = auth_server,
    id = "auth",
    check_credentials = check_credentials(credentials)
  )
  
  output$res_auth <- renderPrint({
    reactiveValuesToList(auth)
  })
  
  observeEvent(session$input$logout,{
    session$reload()
  })
  
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Hello, 
You're right there's no logout button added when using `auth_ui`. You're logic is good, I can wrap this into a new module "logout", or maybe implement this directly in `auth_ui` ?

Victor

**Comment by yusuzech** [comment]
I think a logout module should provide more flexibility. People may want to create custom logout UI and bind "logout" logic to it.

**Comment by vikram-rawat** [comment]
I too want to create my own button for logout and admin panel is there a way i can define them ???

**Comment by Wladimir-Sanyer** [comment]
good solution, although if we only want the fab button to appear after logging into an auth_ui (), do you have any idea how to do this? In other words I want it to only appear after logging in app.

**Comment by maxto** [comment]
> good solution, although if we only want the fab button to appear after logging into an auth_ui (), do you have any idea how to do this? In other words I want it to only appear after logging in app.

Hi, you can use `shinyjs` package to hide fab_button on load and show it later inside the observer after user auth.

```
library(shiny)
library(shinymanager)
library(shinyjs)

# data.frame with credentials info
credentials <- data.frame(
  user = c("admin", "quest"),
  password = c("admin", "quest"),
  stringsAsFactors = FALSE
)

# app
ui <- tagList(
  shinyjs::useShinyjs(),
  
  auth_ui(id = "auth"),
  
  shinyjs::hidden(tags$div(id = "fab_btn_div",fab_button(
    actionButton(
      inputId = "logout",
      label = NULL,
      tooltip = "Logout",
      icon = icon("sign-out")
    ))
  )),
  
  
  navbarPage(title = "navbar",
             tabPanel("Tab1",h1("Tab1")),
             tabPanel("Tab2",h1("Tab2"))
  )
)

server <- function(input, output, session) {
  
  # authentication module
  auth <- callModule(
    module = auth_server,
    id = "auth",
    check_credentials = check_credentials(credentials)
  )
  
  observe({
    req(auth$user)
    shinyjs::show("fab_btn_div")
  })
  
  output$res_auth <- renderPrint({
    reactiveValuesToList(auth)
  })
  
  observeEvent(session$input$logout,{
    session$reload()
  })
  
}

shinyApp(ui, server)
```
