### ISSUE TITLE
Disconnected from server before login

### ISSUE THREAD

**Issue by SebastienGrall** [datastorm-open/shinymanager#70]
Hello,

First, thanks for this package! 
I've tried to secure my app (without SQL database) but just after seeing the authentication page I'm disconnected from the server

![disconnected](https://user-images.githubusercontent.com/47323751/97276430-73ccc680-1837-11eb-879d-2d41826f8d86.png)

I've checked my logs : 

>...
Listening on http://127.0.0.1:39723
Warning: Error in : Problem with `filter()` input `..1`.
✖ Input `..1` must be of size 20602 or 1, not size 0.
ℹ Input `..1` is `Station == input$station`.
  63: <Anonymous>
Warning: Error in : Problem with `filter()` input `..1`.
✖ Input `..1` must be of size 20602 or 1, not size 0.
ℹ Input `..1` is `Station == input$station`.
  64: <Anonymous>
Warning: Error in : Problem with `filter()` input `..1`.
...

> 

I use 3 files : global.R, server.R and ui.R

First use of filter function in my server.R 

`output$titre <- renderText({
      
      
      migrateurs<-subset(migrateurs,Station == data$clickedMarker$id)
      
      data_stac_non_seino<-subset(data_stac_non_seino,Station == data$clickedMarker$id)
      
      return(if(is.null(data$clickedMarker$id)){NULL}
             else{
               if(sum(as.numeric(unique(migrateurs %>%
                                        filter(Station == data$clickedMarker$id) %>%
                                        filter(Date==max(Date)) %>%
                                        .[[1]])))==0){
                 if(sum(as.numeric(unique(data_stac_non_seino %>%
                                          filter(Station==data$clickedMarker$id) %>%
                                          filter(MAJ==max(MAJ)) %>%
                                          .[[1]])
                                   
                                   
                 ))==0){NULL}else{paste("<b>Remontées annuelles")}
                 
               }else{paste("<b>Remontées annuelles")}
             })
      
      })`
 
Sébastien

**Comment by pvictor** [comment]
Hello,

This error is caused by using `NULL` in `dplyr::filter`, e.g. : 

```r
dplyr::filter(iris, Species == NULL)
```

This might be solved using : 

```r
req(data$clickedMarker$id)
```

at the start of any reactive context where the value is used.

Victor

**Comment by SebastienGrall** [comment]
Works perfectly, thanks Victor
