### ISSUE TITLE
Admin Logs not correctly recording users

### ISSUE THREAD

**Issue by ferguskeatinge** [datastorm-open/shinymanager#71]
I have a shiny application that utilizes Shiny Manager, with multiple admins.

I believe the Admin logs page is not correctly showing the number or users that are accessing the application. Our server logs indicate far more than what the logs page is recording.

Many of our uses do not log out of the application, they simple exit their browser without pressing the log out button, could this be contributing to the issue?

Any advice on how to correctly get the admin page to record users?

Thank you.

**Comment by bthieurmel** [comment]
Hi,

I find a problem : if a admin connect the app, show the admin page, on go back to the app for example, we count two connection on logs page.. I'll try to correct that right now

Log out is not a bug / problem in count. If user logout using shinymanager, we save the date of logout on the same log data.

**Comment by bthieurmel** [comment]
Admin count / logs is fix
