### ISSUE TITLE
Shinymanager Login Does Not Time Out 

### ISSUE THREAD

**Issue by JordanWrong7** [datastorm-open/shinymanager#8]
This is my first github post so I apologize in advance if I did not format something properly. 

I have an application that I am currently hosting on shinyapps.io. Here is the app. https://financialtrading.shinyapps.io/earningsedge/. The problem is, the login page does not time out and it actually keeps eating away at my usage time. 

For example, i left the login page open on a tab all day. Here is what my shinyapps.io usage time looks like. 
![Screen Shot 2019-09-25 at 1 31 19 AM](https://user-images.githubusercontent.com/55778452/65571977-96095c00-df34-11e9-83b1-e6e620753b21.png)

What you notice is the constant 1 connection that never disconnected. 

What I am expecting is, the login page times out just like the application does. 

You can find some toy code on my StackOverflow question here. https://stackoverflow.com/questions/58001580/login-screen-for-my-shiny-app-does-not-time-out?noredirect=1#comment102433508_58001580

**Comment by pvictor** [comment]
Hello,
Sorry for the late answer, this should be fixed.
I've deployed a demo on shinyapp.io (https://dreamrs.shinyapps.io/shinymanager-demo/), the application correctly time out.
Re-install from GitHub to make it work.

Victor

**Comment by JordanWrong7** [comment]
thanks pvictor! better late than never

**Comment by klin333** [comment]
It might be worth noting in the documentation for secure_server(), that non-zero timeout values _prevents_ shinyapps.io from timing out. Otherwise it seems counterintuitive that disabling a timeout in shinymanager is the thing that's required to enable the timeout in shinyapps.io
