### ISSUE TITLE
New user automatically deleted from credentials.sqlite after one day

### ISSUE THREAD

**Issue by cherif40** [datastorm-open/shinymanager#86]
Hi DataStorm, 
After deploy my app in shinyapp.io, when I add a new user to sqlite database with add user in the admin section, the new user will delete the next day.
Thanks

**Comment by pvictor** [comment]
Hello,

There's no persistent data storage on shinyapps.io, so no way to add new users and update the database.

Victor

**Comment by cherif40** [comment]
Hello,

It's true, I forgot to tell you that I used the shinymanager package, and it's in the admin part that new users don't stay long.

Cherif

**Comment by pvictor** [comment]
The SQLite database will be re-initialised when user quit the application on shinyapps.io.
You can read more here: https://docs.rstudio.com/shinyapps.io/Storage.html
Currently we can't do anything to solve this.

Victor

**Comment by cherif40** [comment]
Thanks you victor for this clarification.

Hatem Cherif 
DATA SCIENTIST
(Modélisation )àAgence Nationale de Protection de l'Environnement
Tél: 71 365 000/ Fax: 71 356 099Mobile: 99 943 973 

    Le lundi 22 mars 2021, 16:39:40 UTC+1, Victor Perrier ***@***.***> a écrit :  
 
 


The SQLite database will be re-initialised when user quit the application on shinyapps.io.
You can read more here: https://docs.rstudio.com/shinyapps.io/Storage.html
Currently we can't do anything to solve this.

Victor
