### ISSUE TITLE
DE Language Support

### ISSUE THREAD

**Issue by aktuare-ASE** [datastorm-open/shinymanager#88]
Hello,

Could you please add support for the German language?

I find this to be a really great package. I am a developer working for a German company and we would really appreciate it!

**Comment by pvictor** [comment]
Hello,

You can change labels displayed in app like this:

```r
set_labels(
  language = "en",
  "Please authenticate" = "Bitte authentifizieren",
  "Username:" = "Benutzername:",
  "Password:" = "Passwort:",
  "Login" = "Anmeldung"
)
```

Complete list of labels is available here: https://github.com/datastorm-open/shinymanager/blob/master/R/language.R

If you want to add support for German directly in the package, you can add a `list` like the one for fench: https://github.com/datastorm-open/shinymanager/blob/cf5b0bf4b3b88cc80d5edde194d6fb876dff280c/R/language.R#L67

Add translations for DT tables : https://github.com/datastorm-open/shinymanager/blob/cf5b0bf4b3b88cc80d5edde194d6fb876dff280c/R/language.R#L235

Add german in this list: https://github.com/datastorm-open/shinymanager/blob/cf5b0bf4b3b88cc80d5edde194d6fb876dff280c/R/language.R#L208 and others in the rest of the script

And here for using language with `secure_app` : https://github.com/datastorm-open/shinymanager/blob/cf5b0bf4b3b88cc80d5edde194d6fb876dff280c/R/secure-app.R#L29

**Comment by aktuare-ASE** [comment]
thank you very much!
