### ISSUE TITLE
Admin Controls in Deployed App

### ISSUE THREAD

**Issue by owbezick** [datastorm-open/shinymanager#89]
I am realizing that my logs do not show on my deployed app (using shinyapps.io). Everything else is working fine.

**Comment by bthieurmel** [comment]
like #99 

There's no persistent data storage on shinyapps.io, you can read more here : https://docs.rstudio.com/shinyapps.io/Storage.html
Your database is lost when the instance is closed, and the one you've pushed when deploying the application will be used.
