### ISSUE TITLE
observeEvent using login button 

### ISSUE THREAD

**Issue by chalioui** [datastorm-open/shinymanager#9]
Question : Need some help use the id of the login button in observeEvent ! Thank you :)

**Comment by pvictor** [comment]
Hello,
When using `auth_ui` ? Button is inside a module, normally you don't have to access its value, result of authentication is available under slot `result` in output of `callModule(auth)`. If you want to access it anyway, value will be accessible with `input[["<MODULE_ID>-go_auth"]]`.

Victor

**Comment by apriandito** [comment]
Have same problem :(
