### ISSUE TITLE
AuthUI inputs not working

### ISSUE THREAD

**Issue by owbezick** [datastorm-open/shinymanager#90]
Using secure_app() works fine, but when trying to use auth_ui to customize the auth modal, the inputs for username and password do not work. I am able to type a few letters into the username field and then i cannot click into username or password after that.

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

**Comment by pvictor** [comment]
Please provide a reproducible example, without the code you used, we cannot help you.

Please reopen this issue if you have a reprex.

Victor
