### ISSUE TITLE
Users are automatically disconneted

### ISSUE THREAD

**Issue by dr4kan** [datastorm-open/shinymanager#91]
It looks like that users are automatically disconnected from the app after some time. 
How to prevent this behavior?
Thanks

**Comment by bthieurmel** [comment]
Hi,

For some security reason (prevent app stay open), there is a default timeout for disconnect if app is not used by user. You can disabled this : 

````
secure_server(
  check_credentials,
  timeout = 0, # default to 15, 0 to disable
  inputs_list = NULL,
  max_users = NULL,
  fileEncoding = "",
  session = shiny::getDefaultReactiveDomain()
)
````

**Comment by dr4kan** [comment]
Thanks
