### ISSUE TITLE
How to use themes correctly

### ISSUE THREAD

**Issue by roman-tremmel** [datastorm-open/shinymanager#92]
I tried several things. For instance to paste the css file in the library path. 

    secure_app(ui, enable_admin = TRUE, theme = "shinymanager/css/slate.min.css")

This loads the theme, but the app is not correctly working.

**Comment by wangbinkarl** [comment]
you should put the css file to the under of www/.

**Comment by pvictor** [comment]
The `theme` argument from `secure_app()` is passed to `shiny::fluidPage()` or `shiny::navbarPage()`. You can use the same value that you will use with those functions (a file located in `www/`, `shinythemes::shinytheme("cosmo")`, ...)

Victor
