### ISSUE TITLE
New users not being saved in admin mode

### ISSUE THREAD

**Issue by marissabarlaz** [datastorm-open/shinymanager#99]
I am having trouble getting new users authenticated on my app. I will go into administrator mode, add a user and password, save and close their information. I have them test the log in and it works, usually within a few hours of creating the new user account. The user then goes to log in again a few days or weeks later and cannot log in and there is no record of their account info in the administrator mode. Sometimes I have to re-add them two or three times before it saves long term. How can I get these usernames to be saved long-term? I am using shinyapps.io to deploy my app. Thank you!

**Comment by pvictor** [comment]
Hello,

There's no persistent data storage on shinyapps.io, you can read more here : https://docs.rstudio.com/shinyapps.io/Storage.html
Your database is lost when the instance is closed, and the one you've pushed when deploying the application will be used.

Victor
